### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by FernandoTBarros** [FernandoTBarros/Werewolf#2]
- [x] '/players' before game begin shows players who already joined
- [x] command: 'achievements' show in users pv their achievements list
- [x] inline command: 'kills' shows top 5 killed players by user
- [x] inline command: 'killedby' shows top 5 players who killed user

**Comment by FernandoTBarros** [comment]
- [x] return space between votes and etc
- [x] confirm player login msgs

**Comment by FernandoTBarros** [comment]
- [x] send msg as a callback when user did not started the bot yet

**Comment by FernandoTBarros** [comment]
- [ ] when 5 nextgame start a new game
- [x] include join button on nextgame on bot
- [ ]  send msg on pv for shot and sk kills
